/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatForm: typeof import('./src/components/modules/home/ChatForm.vue')['default']
    ChatHeader: typeof import('./src/components/modules/chat/ChatHeader.vue')['default']
    ChatMessage: typeof import('./src/components/modules/chat/ChatMessage.vue')['default']
    ChatMessageForm: typeof import('./src/components/modules/chat/ChatMessageForm.vue')['default']
    ChatMessageList: typeof import('./src/components/modules/chat/ChatMessageList.vue')['default']
    ChatParticipantAvatar: typeof import('./src/components/modules/chat/ChatParticipantAvatar.vue')['default']
    ChatParticipantList: typeof import('./src/components/modules/chat/ChatParticipantList.vue')['default']
    CreateChatButton: typeof import('./src/components/modules/home/CreateChatButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    JoinChatButton: typeof import('./src/components/modules/home/JoinChatButton.vue')['default']
    JoinChatForm: typeof import('./src/components/modules/home/JoinChatForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserChatsTable: typeof import('./src/components/modules/home/UserChatsTable.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
